apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.web_background.name  }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{  .Values.web_background.name  }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{  .Values.web_background.name  }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name:  {{  .Values.web_background.container.name  }}
          image:  {{  .Values.web_background.container.image  }}
          resources:
            requests:
              cpu:  {{  .Values.web_background.container.cpu  }}
              memory:  {{  .Values.web_background.container.memory  }}
          volumeMounts:
            - name: nfs
              mountPath: "/mnt/openstudio"
          env:
            - name: OS_SERVER_NUMBER_OF_WORKERS
              value: ${OS_SERVER_NUMBER_OF_WORKERS}
            - name: QUEUES
              value: background,analyses
          command: ["/usr/local/bin/start-web-background"]
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-pvc
