apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{  .Values.web_background.name  }}
spec:
  replicas: {{  .Values.web_background.replicas  }}
  selector:
    matchLabels:
      app: {{  .Values.web_background.name  }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{  .Values.web_background.name  }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodegroup
                    operator: In
                    values:
                      - web-group
      containers:
        - name:  {{  .Values.web_background.container.name  }}
          image:  {{  .Values.web_background.container.image  }}
          imagePullPolicy: Always
          resources:
            requests:
              cpu:  {{  .Values.web_background.container.resources.requests.cpu  }}
              memory:  {{  .Values.web_background.container.resources.requests.memory  }}
          volumeMounts:
            - name: nfs
              mountPath: "/mnt/openstudio"
          env:
            - name: OS_SERVER_NUMBER_OF_WORKERS
              value: {{ .Values.rserve.number_of_workers | quote }}
            - name: QUEUES
              value: background,analyses
            - name: SECRET_KEY_BASE
              value: {{ .Values.web.secret_key_value }}
            - name: REDIS_URL
              value: {{ .Values.redis_svc.url  }}
            - name: MONGO_USER
              value: {{ .Values.db.username }}
            - name: MONGO_PASSWORD
              value: {{ .Values.db.password }}
          command: ["/usr/local/bin/start-web-background"]
          livenessProbe:
            exec:
              command: ["grep", "-qs", "/mnt/openstudio ",  "/proc/mounts"]
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 3
      priorityClassName: high-priority
      volumes:
        - name: nfs
          persistentVolumeClaim:
            claimName: nfs-pvc
