apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openstudio.redisName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ default "redis" .Values.redis.label }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ default "redis" .Values.redis.label }}
        release: {{ .Release.Name }}
    spec:
      {{- include "openstudio.affinityForRole" (dict "root" . "role" "web") | nindent 6 }}
      containers:
        - name: {{ default "redis" .Values.redis.container.name  }}
          image: {{ .Values.redis.container.image  }}
          resources:
            requests:
              cpu:  {{  .Values.redis.container.resources.requests.cpu  }}
              memory:  {{  .Values.redis.container.resources.requests.memory  }}
          ports:
            - containerPort: {{ default 6379 .Values.redis.container.port }}
          volumeMounts:
            - mountPath: /data
              name: redis
          env:
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "openstudio.secretName" . }}
                  key: {{ include "openstudio.secretKeyRedisPassword" . }}
          command: ["/bin/sh", "-c"]
          args:
            - exec redis-server --appendonly yes --requirepass "$REDIS_PASSWORD"
      volumes:
        - name: redis
          persistentVolumeClaim:
            claimName: {{ include "openstudio.redisName" . }}
