apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.redis.name  }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.redis.name  }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ .Values.redis.name  }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Values.redis.container.name  }}
          image: {{ .Values.redis.container.image  }}
          resources:
            requests:
              cpu:  {{  .Values.redis.container.resources.requests.cpu  }}
              memory:  {{  .Values.redis.container.resources.requests.memory  }}
          ports:
            - containerPort: {{ .Values.redis.container.port  }}
          volumeMounts:
            - mountPath: /data
              name: {{ .Values.redis.name }}
          args: ["redis-server", "--appendonly yes", "--requirepass", "{{ .Values.redis.password  }}"]
      priorityClassName: high-priority
      volumes:
        - name: {{ .Values.redis.name }}
          persistentVolumeClaim:
            claimName: {{ .Values.redis.name }}
