apiVersion: v1
kind: Service
metadata:
  name: {{ include "openstudio.redisServiceName" . }}
spec:
  selector:
    app: {{ default "redis" .Values.redis.label }}
    release: {{ .Release.Name }}
  ports:
    - name: redis
      protocol: TCP
      port: {{ default 6379 (get ((get .Values "redis_svc") | default (dict)) "port") }}
