apiVersion: v1
kind: Service
metadata:
  name: {{ default "queue" (get ((get .Values "redis_svc") | default (dict)) "name") }}
spec:
  selector:
    app: redis
    release: {{ .Release.Name }}
  ports:
    - name: redis
      protocol: TCP
      port: {{ default 6379 (get ((get .Values "redis_svc") | default (dict)) "port") }}
