kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "openstudio.redisName" . }}
spec:
  storageClassName: {{ default (include "openstudio.defaultAppPersistenceStorageClass" .) .Values.redis.persistence.storageClass | quote }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage:  {{ .Values.redis.persistence.size }}