# A simple example of ClusterConfig object with two nodegroups:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: openstudio-server-03
  region: us-west-2
  version: "1.27"


vpc:
  clusterEndpoints:
    privateAccess: true

managedNodeGroups:
  - name: worker-node-group-spot-2a
    instanceTypes: ["c7i.48xlarge", "c7a.48xlarge", "c7i.metal-48xl", "c7a.metal-48xl"]
    minSize: 0
    maxSize: 5
    desiredCapacity: 0
    maxPodsPerNode: 360
    registryQps: 0
    labels:
      nodegroup: worker-group
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        cni: true
    propagateASGTags: true
    spot: true
    ssh:
      allow: true
      # Update publicKeyPath for your public key
      publicKeyPath: ~/.ssh/id_rsa_179d.pub
    # availabilityZones: ["us-west-2a"]
    subnets:
      - subnet-08a05df026b4ec9a8
      - subnet-00ea3f10afdc9fb8e
    volumeSize: 1500
    volumeType: gp3
    tags:
      'org': 'nrel179d'
      'billingId': '230030'
      'cluster-autoscaler.kubernetes.io/safe-to-evict': 'false'
    updateConfig:
      maxUnavailable: 1

  - name: worker-node-group-spot-2c
    instanceTypes: ["c7i.48xlarge", "c7a.48xlarge", "c7i.metal-48xl", "c7a.metal-48xl"]
    minSize: 0
    maxSize: 16
    desiredCapacity: 0
    maxPodsPerNode: 360
    registryQps: 0
    labels:
      nodegroup: worker-group
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        cni: true
    propagateASGTags: true
    spot: true
    ssh:
      allow: true
      # Update publicKeyPath for your public key
      publicKeyPath: ~/.ssh/id_rsa_179d.pub
    # availabilityZones: ["us-west-2c"]
    subnets:
      - subnet-00c5a82bb58556223
      - subnet-0027c0fd03f5cb2bb
      - subnet-099feb77ea09bd101
    volumeSize: 1500
    volumeType: gp3
    tags:
      'org': 'nrel179d'
      'billingId': '230030'
      'cluster-autoscaler.kubernetes.io/safe-to-evict': 'false'
    updateConfig:
      maxUnavailable: 1

  - name: worker-node-group-spot-2d
    instanceTypes: ["c7i.48xlarge", "c7a.48xlarge", "c7i.metal-48xl", "c7a.metal-48xl"]
    minSize: 0
    maxSize: 5
    desiredCapacity: 0
    maxPodsPerNode: 360
    registryQps: 0
    labels:
      nodegroup: worker-group
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
        cni: true
    propagateASGTags: true
    spot: true
    ssh:
      allow: true
      # Update publicKeyPath for your public key
      publicKeyPath: ~/.ssh/id_rsa_179d.pub
    # availabilityZones: ["us-west-2d"]
    subnets:
      - subnet-04bbcd385d4d482cc
    volumeSize: 1500
    volumeType: gp3
    tags:
      'org': 'nrel179d'
      'billingId': '230030'
      'cluster-autoscaler.kubernetes.io/safe-to-evict': 'false'
    updateConfig:
      maxUnavailable: 1