apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: openstudio-server-03
  region: us-west-2
  version: "1.34"

vpc:
  clusterEndpoints:
    privateAccess: true

managedNodeGroups:
  - name: web-node-group-bottlerocket-graviton-v1
    instanceType: m7g.8xlarge
    amiFamily: Bottlerocket
    minSize: 0
    maxSize: 6
    desiredCapacity: 1
    labels:
      nodegroup: web-group
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    subnets:
      - subnet-08a05df026b4ec9a8
    volumeSize: 550
    volumeType: gp3
    tags:
      'org': 'nrel179d'
      'billingId': '230030'
    updateConfig:
      maxUnavailable: 1

  - name: worker-node-group-spot-2a-graviton
    instanceTypes: ["c8g.48xlarge", "m8g.48xlarge", "r8g.48xlarge"]
    amiFamily: AmazonLinux2023
    minSize: 0
    maxSize: 5
    desiredCapacity: 0
    maxPodsPerNode: 360
    labels:
      nodegroup: worker-group
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
    propagateASGTags: true
    spot: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    subnets:
      - subnet-08a05df026b4ec9a8
      - subnet-00ea3f10afdc9fb8e
    volumeSize: 1500
    volumeType: gp3
    tags:
      'org': 'nrel179d'
      'billingId': '230030'
      'cluster-autoscaler.kubernetes.io/safe-to-evict': 'false'
    updateConfig:
      maxUnavailable: 1

  - name: worker-node-group-spot-2c-graviton
    instanceTypes: ["c8g.48xlarge", "m8g.48xlarge", "r8g.48xlarge"]
    amiFamily: AmazonLinux2023
    minSize: 0
    maxSize: 16
    desiredCapacity: 0
    maxPodsPerNode: 360
    labels:
      nodegroup: worker-group
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
    propagateASGTags: true
    spot: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    subnets:
      - subnet-00c5a82bb58556223
      - subnet-0027c0fd03f5cb2bb
      - subnet-099feb77ea09bd101
    volumeSize: 1500
    volumeType: gp3
    tags:
      'org': 'nrel179d'
      'billingId': '230030'
      'cluster-autoscaler.kubernetes.io/safe-to-evict': 'false'
    updateConfig:
      maxUnavailable: 1

  - name: worker-node-group-spot-2d-graviton
    instanceTypes: ["c8g.48xlarge", "m8g.48xlarge", "r8g.48xlarge"]
    amiFamily: AmazonLinux2023
    minSize: 0
    maxSize: 5
    desiredCapacity: 0
    maxPodsPerNode: 360
    labels:
      nodegroup: worker-group
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
    propagateASGTags: true
    spot: true
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/id_rsa.pub
    subnets:
      - subnet-04bbcd385d4d482cc
    volumeSize: 1500
    volumeType: gp3
    tags:
      'org': 'nrel179d'
      'billingId': '230030'
      'cluster-autoscaler.kubernetes.io/safe-to-evict': 'false'
    updateConfig:
      maxUnavailable: 1
