# A simple example of ClusterConfig object with two nodegroups:
--- 
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: openstudio-server-03
  region: us-west-2
  version: "1.34"


vpc:
  clusterEndpoints:
    privateAccess: true

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: ebs-csi-controller-sa
        namespace: kube-system
      wellKnownPolicies:
        ebsCSIController: true

managedNodeGroups:
  - name: worker-node-group-spot-03
    amiType: Bottlerocket_x86_64
    instanceTypes: ["c7a.48xlarge", "c7i.48xlarge", "c7i.metal-48xl", "c7a.metal-48xl"]
    minSize: 0
    maxSize: 70
    desiredCapacity: 0
    maxPodsPerNode: 250
    registryQps: 0
    labels:
      nodegroup: worker-group
    privateNetworking: true
    iam:
      withAddonPolicies:
        autoScaler: true
        externalDNS: true
        certManager: true
        ebs: true
    spot: true
    volumeSize: 1500
    volumeType: gp3
    tags:
      'org': 'calc179d'
      'billingId': '230043'
    subnets:
      - subnet-04bbcd385d4d482cc
      - subnet-00c5a82bb58556223
      - subnet-08a05df026b4ec9a8
      - subnet-0027c0fd03f5cb2bb
      - subnet-00ea3f10afdc9fb8e
    updateConfig:
      maxUnavailable: 1  # Or use maxUnavailablePercentage

addons:
  - name: aws-ebs-csi-driver
    wellKnownPolicies:
      ebsCSIController: true
