apiVersion: v1
kind: Pod
metadata:
  name: ssh-jump
  namespace: openstudio-server
spec:
  nodeSelector:
    capi.stackhpc.com/node-group: web
  containers:
  - name: ubuntu
    image: ubuntu:latest
    command: ["sleep", "3600"]
