apiVersion: v1
kind: Service
metadata:
  name: {{ include "openstudio.webServiceName" . }}
{{ $webSvc := (get .Values "web_svc") | default (dict) }}
{{ $web := (get .Values "web") | default (dict) }}
{{ $webSvcPorts := (get $webSvc "ports") | default (dict) }}
spec:
  selector:
    app: {{ default (default "web" (get $web "label")) (get $webSvc "label") }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ default 80 (get $webSvcPorts "http") }}
    - name: https
      protocol: TCP
      port:  {{ default 443 (get $webSvcPorts "https") }}
