apiVersion: v1
kind: Service
metadata:
  name: {{ default "web" .Values.web_svc.name }}
{{ $webSvc := (get .Values "web_svc") | default (dict) }}
{{ $webSvcPorts := (get $webSvc "ports") | default (dict) }}
spec:
  selector:
    app: web
    release: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: {{ default 80 (get $webSvcPorts "http") }}
    - name: https
      protocol: TCP
      port:  {{ default 443 (get $webSvcPorts "https") }}
