apiVersion: v1
kind: Service
metadata:
  name: {{ include "openstudio.dbName" . }}
{{ $dbContainer := (get .Values.db "container") | default (dict) }}
{{ $dbContainerPorts := (get $dbContainer "ports") | default (dict) }}
spec:
  selector:
    app: {{ default "db" .Values.db.label }}
    release: {{ .Release.Name }}
  ports:
    - name: db
      protocol: TCP
      port: {{ default 27017 (get $dbContainerPorts "db_port") }}
