apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.name  }}
spec:
  selector:
    app: {{ .Values.db.label  }}
    release: {{ .Release.Name }}
  ports:
    - name: {{ .Values.db.name  }}
      protocol: TCP
      port: {{ .Values.db.container.ports.db_port }}
