{{- $preDeleteHook := default (dict) .Values.hooks.preDeleteCleanup -}}
{{- if default true (get $preDeleteHook "enabled") }}
apiVersion: batch/v1
kind: Job
metadata:
  name: nfs-client-cleanup
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-delete
    "helm.sh/hook-weight": "3"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  backoffLimit: 1
  template:
    metadata:
      name: nfs-client-cleanup
    spec:
      containers:
        - name: kubectl
          image: "bitnami/kubectl:1.31"
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            capabilities:
              drop:
                - ALL
          imagePullPolicy: "IfNotPresent"
          command:
          - /bin/sh
          - -c
          - >
              kubectl -n {{ .Release.Namespace }} delete deployment web --ignore-not-found=true --wait=true --timeout=180s;
              kubectl -n {{ .Release.Namespace }} delete deployment web-background --ignore-not-found=true --wait=true --timeout=180s;
              kubectl -n {{ .Release.Namespace }} delete deployment rserve --ignore-not-found=true --wait=true --timeout=180s;
      restartPolicy: Never
{{- end }}
