{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "localRegistry.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "localRegistry.labels" . | nindent 4 }}
{{- end }}