apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.worker_hpa.name  }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.worker.name  }}
  minReplicas: {{ .Values.worker_hpa.minReplicas  }}
  maxReplicas: {{ .Values.worker_hpa.maxReplicas  }}
  behavior:
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.worker_hpa.stabilizationWindowSeconds  }}
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.worker_hpa.targetCPUUtilizationPercentage  }}
