apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.worker.name   }}
  annotations:
    cluster-autoscaler.kubernetes.io/safe-to-evict: "false"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.worker.name }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.worker.name }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        {{- include "openstudio.nodeGroupAffinity" (dict "root" . "role" "worker") | nindent 8 }}
      containers:
        - name: {{ .Values.worker.container.name   }}
          image: {{ .Values.worker.container.image   }}
          imagePullPolicy: IfNotPresent
          lifecycle:
            preStop:
              exec:
                command: ['/bin/sh', '-c', 'echo "Creating kill.worker file" >&2; touch /opt/openstudio/server/bin/kill.worker; echo "Sending QUIT signal to Resque" >&2; pkill -f -QUIT resque; echo "Waiting for Ruby or OpenStudio processes to end" >&2; while [ $(eval "pgrep -c ruby") -gt 1 ] || [ $(eval "pgrep -c openstudio") -gt 0 ]; do sleep 15; echo "Still waiting..." >&2; done; echo "Killing remaining processes" >&2; pkill -P 1;']
          resources:
            requests:
              cpu:  {{  .Values.worker.container.resources.requests.cpu  }}
              memory:  {{  .Values.worker.container.resources.requests.memory  }}
          volumeMounts:
            - name: osdata-worker
              mountPath: "/mnt/openstudio"
          env:
            - name:  QUEUES
              value: requeued,simulations
            - name:  COUNT
              value: "1"
            - name: SECRET_KEY_BASE
              value: {{ .Values.web.secret_key_value }}
            - name: REDIS_URL
              value: {{ .Values.redis_svc.url  }}
            - name: MONGO_USER
              value: {{ .Values.db.username }}
            - name: MONGO_PASSWORD
              value: {{ .Values.db.password }}
          command: ["/usr/local/bin/start-workers"]
      terminationGracePeriodSeconds: {{ .Values.worker.container.terminationGracePeriodSeconds }} # for long openstudio jobs.
      priorityClassName: low-priority
      volumes:
        - name: osdata-worker
          emptyDir: {}
