apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "openstudio.workerName" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ default "worker" .Values.worker.label }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ default "worker" .Values.worker.label }}
        release: {{ .Release.Name }}
    {{ $priorityClasses := default (dict) .Values.priorityClasses }}
    {{ $redis := default (dict) .Values.redis }}
    spec:
      {{- include "openstudio.affinityForRole" (dict "root" . "role" "worker") | nindent 6 }}
      {{- if (default true (get $priorityClasses "enabled")) }}
      priorityClassName: {{ default "low-priority" (get $priorityClasses "lowName") }}
      {{- end }}
      containers:
        - name: {{ default "worker" .Values.worker.container.name }}
          image: {{ default (include "openstudio.serverImage" .) .Values.worker.container.image }}
          imagePullPolicy: Always
          lifecycle:
            preStop:
              exec:
                command: ['/bin/sh','-c', 'pkill -3 -f resque;  while [ $(eval "pgrep -c ruby") -gt 1 ] || [ $(eval "pgrep -c openstudio") -gt 0 ]  ; do sleep 300;  done; pkill -P 1;']
          resources:
            requests:
              cpu:  {{  .Values.worker.container.resources.requests.cpu  }}
              memory:  {{  .Values.worker.container.resources.requests.memory  }}
          volumeMounts:
            - name: osdata-worker
              mountPath: "/mnt/openstudio"
          env:
            - name:  QUEUES
              value: {{ .Values.worker.queues | quote }}
            - name:  QUEUE
              value: {{ .Values.worker.queues | quote }}
            - name:  COUNT
              value: "1"
            - name: SECRET_KEY_BASE
              valueFrom:
                secretKeyRef:
                  name: {{ include "openstudio.secretName" . }}
                  key: {{ include "openstudio.secretKeyWebSecret" . }}
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "openstudio.secretName" . }}
                  key: {{ include "openstudio.secretKeyRedisPassword" . }}
            - name: REDIS_URL
              value: {{ default (printf "redis://:$(REDIS_PASSWORD)@%s:6379" (include "openstudio.redisServiceName" .)) (get $redis "url") | quote }}
            - name: MONGO_USER
              valueFrom:
                secretKeyRef:
                  name: {{ include "openstudio.secretName" . }}
                  key: {{ include "openstudio.secretKeyDbUsername" . }}
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ include "openstudio.secretName" . }}
                  key: {{ include "openstudio.secretKeyDbPassword" . }}
          command: ["/usr/local/bin/start-workers"]
      terminationGracePeriodSeconds: {{ .Values.worker.container.terminationGracePeriodSeconds }} # for long openstudio jobs.
      volumes:
        - name: osdata-worker
          emptyDir: {}
