{{- if eq (include "openstudio.workerAutoscalingMode" .) "hpa" }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "openstudio.workerHpaName" . }}
  annotations:
    helm.sh/resource-policy: keep
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "openstudio.workerName" . }}
  minReplicas: {{ .Values.worker_hpa.minReplicas  }}
  maxReplicas: {{ .Values.worker_hpa.maxReplicas  }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 10
      policies:
      - type: Pods
        value: 32
        periodSeconds: 15
      - type: Percent
        value: 200
        periodSeconds: 15
      selectPolicy: Max
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.worker_hpa.stabilizationWindowSeconds  }}
      policies:
      - type: Percent
        value: 25
        periodSeconds: 60
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.worker_hpa.targetCPUUtilizationPercentage  }}
{{- end }}
