apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.worker_hpa.name  }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.worker.name  }}
  minReplicas: {{ .Values.worker_hpa.minReplicas  }}
  maxReplicas: {{ .Values.worker_hpa.maxReplicas  }}
  targetCPUUtilizationPercentage: {{ .Values.worker_hpa.targetCPUUtilizationPercentage  }}
