# Small OpenStack overlay for the external NFS-class deployment.

global:
  provider:
    name: "openstack"

nfs-server-provisioner:
  enabled: false
  persistence:
    size: 5Gi
    storageClass: "nfs-client"
  storageClass:
    allowVolumeExpansion: false
    mountOptions:
      - vers=4
      - sync

db:
  persistence:
    size: 2Gi
    storageClass: "nfs-client"
  container:
    resources:
      requests:
        cpu: 1
        memory: "4Gi"

nfs_pvc:
  storage: "5Gi"
  storageClass: "nfs-client"

redis:
  persistence:
    size: 1Gi
    storageClass: "nfs-client"
  container:
    resources:
      requests:
        cpu: 0.25
        memory: "1Gi"

rserve:
  number_of_workers: "1"
  container:
    resources:
      requests:
        cpu: 1
        memory: "2Gi"

web_background:
  replicas: 1
  container:
    resources:
      requests:
        cpu: 0.25
        memory: "512Mi"

web:
  container:
    resources:
      requests:
        cpu: 1
        memory: "2Gi"

worker:
  container:
    resources:
      requests:
        cpu: 700m
        memory: "900Mi"

worker_hpa:
  minReplicas: 2
  maxReplicas: 20
  targetCPUUtilizationPercentage: 50
  stabilizationWindowSeconds: 3600
