apiVersion: v1
kind: Service
metadata:
  name: {{ default "rserve" .Values.rserve_svc.name }}
spec:
  selector:
    app: {{ default "rserve" .Values.rserve.label }}
    release: {{ .Release.Name }}
  ports:
    - name: rserve
      protocol: TCP
      port: {{ default 6311 .Values.rserve_svc.port }}
