apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rserve.name }}
  labels:
    release: {{ .Release.Name }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rserve.name }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.rserve.name }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - {{ .Values.web.label }}
                topologyKey: kubernetes.io/hostname
        {{- include "openstudio.nodeGroupAffinity" (dict "root" . "role" "web") | nindent 8 }}
      containers:
        - name: {{ .Values.rserve.container.name }}
          image: {{ include "openstudio.imageWithRegistry" (dict "root" $ "image" .Values.rserve.container.image) | quote }}
          resources:
            requests:
              cpu: {{ .Values.rserve.container.resources.requests.cpu }}
              memory: {{ .Values.rserve.container.resources.requests.memory }}
            {{- include "openstudio.resourceLimits" .Values.rserve.container.resources.limits | nindent 12 }}
          volumeMounts:
            - name: osdata
              mountPath: "/mnt/openstudio"
          env:
            - name: OS_SERVER_NUMBER_OF_WORKERS
              value: {{ include "openstudio.webBackgroundWorkers" . | quote }}
            - name: SECRET_KEY_BASE
              value: {{ .Values.web.secret_key_value | quote }}
            - name: REDIS_URL
              value: {{ .Values.redis_svc.url | quote }}
            - name: MONGO_USER
              value: {{ .Values.db.username | quote }}
            - name: MONGO_PASSWORD
              value: {{ .Values.db.password | quote }}
          livenessProbe:
            exec:
              command: ["grep", "-qs", "/mnt/openstudio ", "/proc/mounts"]
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 3
      priorityClassName: high-priority
      terminationGracePeriodSeconds: 60
      volumes:
        - name: osdata
          persistentVolumeClaim:
            claimName: nfs-pvc