apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.rserve.name  }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ .Values.rserve.name }}
      release: {{ .Release.Name }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: {{ .Values.rserve.name }}
        release: {{ .Release.Name }}
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: nodegroup
                    operator: In
                    values:
                      - web-group
      containers:
        - name: {{ .Values.rserve.container.name }}
          image: {{ .Values.rserve.container.image }}
          resources:
            requests:
              cpu:  {{  .Values.rserve.container.resources.requests.cpu  }}
              memory:  {{  .Values.rserve.container.resources.requests.memory  }}
          volumeMounts:
            - name: osdata
              mountPath: "/mnt/openstudio"
          env:
             - name: OS_SERVER_NUMBER_OF_WORKERS
               value: {{ .Values.rserve.number_of_workers | quote }}
             - name: SECRET_KEY_BASE
               value: {{ .Values.web.secret_key_value }}
             - name: REDIS_URL
               value: {{ .Values.redis_svc.url  }}
             - name: MONGO_USER
               value: {{ .Values.db.username }}
             - name: MONGO_PASSWORD
               value: {{ .Values.db.password }}
          livenessProbe:
            exec:
              command: ["grep", "-qs", "/mnt/openstudio ",  "/proc/mounts"]
            initialDelaySeconds: 5
            periodSeconds: 30
            timeoutSeconds: 30
            failureThreshold: 3
      priorityClassName: high-priority
      volumes:
        - name: osdata
          persistentVolumeClaim:
            claimName: nfs-pvc
