apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd
{{ if eq .Values.provider.name "aws" }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
allowVolumeExpansion: true
{{ end }}
{{ if eq .Values.provider.name "google" }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
allowVolumeExpansion: true
{{ end }}
{{ if eq .Values.provider.name "azure" }}
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
  storageaccounttype: StandardSSD_LRS
allowVolumeExpansion: true
{{ end }}
{{ if eq .Values.provider.name "openstack" }}
provisioner: kubernetes.io/cinder
parameters:
  availability: nova
  type: __DEFAULT__
allowVolumeExpansion: true
{{ end }}
reclaimPolicy: Delete
mountOptions:
  - debug
volumeBindingMode: Immediate
allowedTopologies:
- matchLabelExpressions:
  - key: nodegroup
    values:
      - web-group
