
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: region2astorageclass
{{ if eq .Values.provider.name "aws" }}
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp3
{{ end }}
{{ if eq .Values.provider.name "google" }}
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-ssd
{{ end }}
{{ if eq .Values.provider.name "azure" }}
provisioner: kubernetes.io/azure-disk
parameters:
  kind: Managed
  storageaccounttype: StandardSSD_LRS
{{ end }}
reclaimPolicy: Delete
mountOptions:
  - debug
volumeBindingMode: Immediate
allowedTopologies:
- matchLabelExpressions:
  - key: topology.kubernetes.io/zone
    values:
    - us-west-2a