apiVersion: v1
kind: Service
{{ $loadBalancer := (get .Values "load_balancer") | default (dict) }}
{{ $ports := (get $loadBalancer "ports") | default (dict) }}
{{ $annotations := (get $loadBalancer "annotations") | default (dict) }}
{{ $sourceRanges := (get $loadBalancer "sourceRanges") | default (list) }}
{{ $providerName := include "openstudio.providerName" . }}
metadata:
  name: {{ default "ingress-load-balancer" (get $loadBalancer "name") }}
  annotations:
{{- if and (eq $providerName "aws") (get $loadBalancer "internal") }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
{{- else if and (eq $providerName "azure") (get $loadBalancer "internal") }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
{{- else if and (eq $providerName "google") (get $loadBalancer "internal") }}
    cloud.google.com/load-balancer-type: "Internal"
{{- else if and (eq $providerName "openstack") (get $loadBalancer "internal") }}
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
{{- end }}
{{- range $k, $v := $annotations }}
    {{ $k }}: {{ $v | quote }}
{{- end }}
spec:
  type: {{ default "LoadBalancer" (get $loadBalancer "type") }}
  externalTrafficPolicy: {{ default (include "openstudio.defaultLoadBalancerExternalTrafficPolicy" .) (get $loadBalancer "externalTrafficPolicy") | quote }}
{{- if gt (len $sourceRanges) 0 }}
  loadBalancerSourceRanges:
{{ toYaml $sourceRanges | nindent 4 }}
{{- end }}
  selector:
    app: {{ default "web" (get $loadBalancer "label") }}
    release: {{ .Release.Name }}
  ports:
    - name: {{ default "http" (get $ports "http_name") }}
      protocol: {{ default "TCP" (get $ports "http_protocol") }}
      port: {{ default 80 (get $ports "http_port") }}
    - name: {{ default "https" (get $ports "https_name") }}
      protocol: {{ default "TCP" (get $ports "https_protocol") }}
      port: {{ default 443 (get $ports "https_port") }}
