apiVersion: v1
kind: Service
{{ $loadBalancer := (get .Values "load_balancer") | default (dict) }}
{{ $providerName := include "openstudio.providerName" . }}
metadata:
  name: ingress-load-balancer
  annotations:
{{- if and (eq $providerName "aws") (get $loadBalancer "internal") }}
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
{{- else if and (eq $providerName "azure") (get $loadBalancer "internal") }}
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
{{- else if and (eq $providerName "google") (get $loadBalancer "internal") }}
    cloud.google.com/load-balancer-type: "Internal"
{{- else if and (eq $providerName "openstack") (get $loadBalancer "internal") }}
    service.beta.kubernetes.io/openstack-internal-load-balancer: "true"
{{- end }}
spec:
  type: {{ default "LoadBalancer" (get $loadBalancer "type") }}
  externalTrafficPolicy: {{ default (include "openstudio.defaultLoadBalancerExternalTrafficPolicy" .) (get $loadBalancer "externalTrafficPolicy") | quote }}
  selector:
    app: {{ default "web" (get $loadBalancer "label") }}
    release: {{ .Release.Name }}
  ports:
    - name: http
      protocol: TCP
      port: 80
    - name: https
      protocol: TCP
      port: 443
