apiVersion: keda.sh/v1alpha1
kind: TriggerAuthentication
metadata:
  annotations:
    meta.helm.sh/release-name: openstudio-server
    meta.helm.sh/release-namespace: openstudio-server
  creationTimestamp: "2026-06-08T12:29:50Z"
  finalizers:
  - finalizer.keda.sh
  generation: 1
  labels:
    app.kubernetes.io/managed-by: Helm
  name: worker-keda-redis-auth
  namespace: openstudio-server
  resourceVersion: "5795144"
  uid: a1e265a3-d0c5-4b8d-8d83-3f745c7cbcbf
spec:
  secretTargetRef:
  - key: redis-password
    name: openstudio-app-secrets
    parameter: password
status:
  scaledobjects: worker
