kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.nfs_pvc.name }}
spec:
  accessModes:
{{- range .Values.nfs_pvc.accessModes }}
    - {{ . | quote }}
{{- end }}
  storageClassName: {{ .Values.nfs_pvc.storageClass | quote }}
  resources:
    requests:
      storage: {{ .Values.nfs_pvc.storage | quote }}