{{- $nfsPvc := default (dict) (get .Values "nfs_pvc") -}}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ include "openstudio.nfsPvcName" . }}
spec:
  accessModes:
{{- range $mode := default (list "ReadWriteMany") (get $nfsPvc "accessModes") }}
    - {{ $mode }}
{{- end }}
  storageClassName: {{ default "nfs" (get $nfsPvc "storage_class") | quote }}
  resources:
    requests:
      storage:  {{ default "2Gi" (get $nfsPvc "storage") }}