apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-nfs-disconnect
  namespace: {{ .Release.Namespace }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ .Release.Name }}-nfs-disconnect
  namespace: {{ .Release.Namespace }}
rules:
  - apiGroups: ["apps"]
    resources: ["deployments", "statefulsets"]
    verbs: ["delete", "list", "get"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["delete", "list", "get", "watch"]
  - apiGroups: [""]
    resources: ["persistentvolumeclaims"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Release.Name }}-nfs-disconnect
  namespace: {{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Release.Name }}-nfs-disconnect
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ .Release.Name }}-nfs-disconnect
  apiGroup: rbac.authorization.k8s.io