{{- if .Values.web.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.web.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.web.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.web_background.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.web_background.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.web_background.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.worker.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.worker.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.worker.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.rserve.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.rserve.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.rserve.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.db.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.db.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.db.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.redis.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.redis.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.redis.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
---
{{- end }}
{{- if .Values.pre_delete_hook.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.pre_delete_hook.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  {{- with .Values.pre_delete_hook.serviceAccount.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
{{- end }}
